// Shared mock data for FreshFinds — single source of truth for all API routes.
// This avoids duplicating vendor/listing data across /api/vendors, /api/listings, /api/search.

const NOW = Date.now();
function minsAgo(m: number) { return new Date(NOW - m * 60000).toISOString(); }
function hoursAgo(h: number) { return new Date(NOW - h * 3600000).toISOString(); }
function daysAgo(d: number) { return new Date(NOW - d * 86400000).toISOString(); }
function pickupToday(hour: number): string {
  const d = new Date();
  d.setHours(hour, 0, 0, 0);
  return d.toISOString();
}
export function expireAfter(postedAtIso: string): string {
  return new Date(new Date(postedAtIso).getTime() + 24 * 3600000).toISOString();
}
export function parseDietaryTags(tags: string | null): string[] {
  if (!tags) return [];
  try { return JSON.parse(tags); } catch { return []; }
}

// ── Cities ──────────────────────────────────────────────────────────
export interface CityDef {
  slug: string;
  name: string;
  state: string;
  stateName: string;
  lat: number;
  lng: number;
  defaultZoom: number;
  zipHint: string;
  tagline: string;
  complianceNote: string;
}

export const CITIES: CityDef[] = [
  { slug: "austin", name: "Austin", state: "TX", stateName: "Texas", lat: 30.2672, lng: -97.7431, defaultZoom: 12, zipHint: "78701", tagline: "Keep it weird, eat it fresh.", complianceNote: "Texas cottage food law ($150K cap, food handler training)" },
  { slug: "nashville", name: "Nashville", state: "TN", stateName: "Tennessee", lat: 36.1627, lng: -86.7816, defaultZoom: 12, zipHint: "37203", tagline: "Music City meets farm-to-table.", complianceNote: "No permit required — follow TN cottage food guidelines" },
  { slug: "knoxville", name: "Knoxville", state: "TN", stateName: "Tennessee", lat: 35.9606, lng: -83.9207, defaultZoom: 12, zipHint: "37902", tagline: "Smoky Mountain flavors, fresh daily.", complianceNote: "No permit required — follow TN cottage food guidelines" },
  { slug: "chattanooga", name: "Chattanooga", state: "TN", stateName: "Tennessee", lat: 35.0456, lng: -85.3097, defaultZoom: 12, zipHint: "37402", tagline: "Scenic city, even sweeter eats.", complianceNote: "No permit required — follow TN cottage food guidelines" },
  { slug: "charlotte", name: "Charlotte", state: "NC", stateName: "North Carolina", lat: 35.2271, lng: -80.8431, defaultZoom: 12, zipHint: "28202", tagline: "Queen City taste, homemade.", complianceNote: "No permit required — follow NC cottage food guidelines" },
  { slug: "raleigh", name: "Raleigh", state: "NC", stateName: "North Carolina", lat: 35.7796, lng: -78.6382, defaultZoom: 12, zipHint: "27601", tagline: "Oak City bakes and beyond.", complianceNote: "No permit required — follow NC cottage food guidelines" },
  { slug: "asheville", name: "Asheville", state: "NC", stateName: "North Carolina", lat: 35.5951, lng: -82.5515, defaultZoom: 12, zipHint: "28801", tagline: "Where the Blue Ridge meets artisan bread.", complianceNote: "No permit required — follow NC cottage food guidelines" },
  { slug: "charleston", name: "Charleston", state: "SC", stateName: "South Carolina", lat: 32.7765, lng: -79.9311, defaultZoom: 13, zipHint: "29401", tagline: "Lowcountry charm, fresh from the oven.", complianceNote: "No permit required — follow SC cottage food guidelines" },
  { slug: "greenville", name: "Greenville", state: "SC", stateName: "South Carolina", lat: 34.8526, lng: -82.3940, defaultZoom: 12, zipHint: "29601", tagline: "Growing fresh in the Upstate.", complianceNote: "No permit required — follow SC cottage food guidelines" },
  { slug: "columbia", name: "Columbia", state: "SC", stateName: "South Carolina", lat: 34.0007, lng: -81.0348, defaultZoom: 12, zipHint: "29201", tagline: "Soda City's sweetest secrets.", complianceNote: "No permit required — follow SC cottage food guidelines" },
  { slug: "richmond", name: "Richmond", state: "VA", stateName: "Virginia", lat: 37.5407, lng: -77.4360, defaultZoom: 12, zipHint: "23219", tagline: "River City bakes it best.", complianceNote: "No permit required — follow VA cottage food guidelines" },
  { slug: "norfolk", name: "Norfolk", state: "VA", stateName: "Virginia", lat: 36.8468, lng: -76.2859, defaultZoom: 12, zipHint: "23510", tagline: "Coastal flavors, homemade love.", complianceNote: "No permit required — follow VA cottage food guidelines" },
  { slug: "fayetteville", name: "Fayetteville", state: "AR", stateName: "Arkansas", lat: 36.0626, lng: -94.1574, defaultZoom: 12, zipHint: "72701", tagline: "Ozark mountain honey and more.", complianceNote: "No permit required — follow AR cottage food guidelines" },
  { slug: "wichita", name: "Wichita", state: "KS", stateName: "Kansas", lat: 37.6872, lng: -97.3301, defaultZoom: 12, zipHint: "67202", tagline: "Sunflower State sweetness.", complianceNote: "No permit required — follow KS cottage food guidelines" },
];

export function getCityBySlug(slug: string): CityDef | undefined {
  return CITIES.find((c) => c.slug === slug.toLowerCase());
}

export function getCityByName(name: string): CityDef | undefined {
  return CITIES.find((c) => c.name.toLowerCase() === name.toLowerCase());
}

export function getCityByState(state: string): CityDef[] {
  return CITIES.filter((c) => c.state === state.toUpperCase());
}

export function getCitiesGroupedByState(): { state: string; stateName: string; cities: CityDef[] }[] {
  const map = new Map<string, { state: string; stateName: string; cities: CityDef[] }>();
  for (const c of CITIES) {
    if (!map.has(c.state)) {
      map.set(c.state, { state: c.state, stateName: c.stateName, cities: [] });
    }
    map.get(c.state)!.cities.push(c);
  }
  return Array.from(map.values());
}

// ── Vendors ──────────────────────────────────────────────────────────
// All IDs: Austin 1–10 are preserved. New vendors start from 11.
export const MOCK_VENDORS: any[] = [
  // ═══ AUSTIN, TX (IDs 1–10) ═══
  { id: 1, businessName: "ATX Sourdough", name: "Maria Rodriguez", email: "maria@atxsourdough.com", lat: 30.2615, lng: -97.732, address: "1200 E 6th St, Austin, TX 78702", photoUrl: "https://images.unsplash.com/photo-1549931319-a545799f7b09?w=600&q=80", categoryName: "Bread & Pastries", categorySlug: "bread-pastries", categoryIcon: "🥖", rating: 4.7, reviewCount: 12, listingCount: 3, hasFreshItems: true, bio: "Hand-crafted sourdough bread using a 100-year-old starter. Baked fresh daily in East Austin.", verified: true, state: "TX", city: "Austin" },
  { id: 2, businessName: "Eastside Eggs", name: "James & Lisa Chen", email: "hello@eastsideeggs.com", lat: 30.2548, lng: -97.7089, address: "2400 Webberville Rd, Austin, TX 78702", photoUrl: "https://images.unsplash.com/photo-1598965675045-8e1e099edc5c?w=600&q=80", categoryName: "Eggs & Dairy", categorySlug: "eggs-dairy", categoryIcon: "🥚", rating: 4.9, reviewCount: 8, listingCount: 2, hasFreshItems: true, bio: "Free-range eggs from happy hens raised right here in East Austin. Farm-fresh daily.", verified: true, state: "TX", city: "Austin" },
  { id: 3, businessName: "Hill Country Honey", name: "Robert Hill", email: "rob@hillcountryhoney.com", lat: 30.2477, lng: -97.9284, address: "8901 TX-71, Austin, TX 78735", photoUrl: "https://images.unsplash.com/photo-1471943311424-646960669fbc?w=600&q=80", categoryName: "Honey & Preserves", categorySlug: "honey-preserves", categoryIcon: "🍯", rating: 4.5, reviewCount: 5, listingCount: 3, hasFreshItems: false, bio: "Raw, unfiltered honey from our hives in the Texas Hill Country.", verified: false, state: "TX", city: "Austin" },
  { id: 4, businessName: "Texas Pie Company", name: "Patricia Johnson", email: "pat@texaspieco.com", lat: 30.2351, lng: -97.7892, address: "4200 S Lamar Blvd, Austin, TX 78704", photoUrl: "https://images.unsplash.com/photo-1568571780765-9276ac2c48c9?w=600&q=80", categoryName: "Desserts & Sweets", categorySlug: "desserts", categoryIcon: "🥧", rating: 4.8, reviewCount: 15, listingCount: 2, hasFreshItems: true, bio: "Award-winning pies made from scratch with Texas pecans, seasonal fruits, and lots of love.", verified: true, state: "TX", city: "Austin" },
  { id: 5, businessName: "Sunset Farms Produce", name: "David & Sarah Martinez", email: "david@sunsetfarmsatx.com", lat: 30.4015, lng: -97.7207, address: "11501 Rock Rose Ave, Austin, TX 78758", photoUrl: "https://images.unsplash.com/photo-1579113800032-c38bd7635818?w=600&q=80", categoryName: "Fresh Produce", categorySlug: "produce", categoryIcon: "🌽", rating: 4.6, reviewCount: 9, listingCount: 3, hasFreshItems: true, bio: "Family-run organic vegetable farm in North Austin. Seasonal produce grown without pesticides.", verified: true, state: "TX", city: "Austin" },
  { id: 6, businessName: "Flower Child Farms", name: "Alice Green", email: "alice@flowerchildfarms.com", lat: 30.2819, lng: -97.7265, address: "1500 Manor Rd, Austin, TX 78722", photoUrl: "https://images.unsplash.com/photo-1561181286-d5ef733c1a54?w=600&q=80", categoryName: "Flowers & Plants", categorySlug: "flowers", categoryIcon: "🌼", rating: 4.4, reviewCount: 3, listingCount: 1, hasFreshItems: true, bio: "Fresh-cut flower bouquets and potted herbs from our urban micro-farm.", verified: false, state: "TX", city: "Austin" },
  { id: 7, businessName: "Taco Tones", name: "Tony Ramirez", email: "tony@tacotones.com", lat: 30.2452, lng: -97.7563, address: "1700 S Congress Ave, Austin, TX 78704", photoUrl: "https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=600&q=80", categoryName: "Food Truck", categorySlug: "food-truck", categoryIcon: "🚚", rating: 4.3, reviewCount: 22, listingCount: 4, hasFreshItems: true, bio: "Breakfast tacos and street food — find us at different spots around South Congress.", verified: true, state: "TX", city: "Austin" },
  { id: 8, businessName: "Mama Lu's Kitchen", name: "Lucia Mendez", email: "lucia@mamalukitchen.com", lat: 30.3340, lng: -97.7020, address: "8500 Research Blvd, Austin, TX 78758", photoUrl: "https://images.unsplash.com/photo-1576866209830-954e6bf8d5e2?w=600&q=80", categoryName: "Meals & Prepared", categorySlug: "meals", categoryIcon: "🍽️", rating: 4.9, reviewCount: 18, listingCount: 2, hasFreshItems: false, bio: "Homemade comfort food — lasagna, enchiladas, and meal prep boxes from a North Austin home kitchen.", verified: true, state: "TX", city: "Austin" },
  { id: 9, businessName: "Bee Sweet Bakery", name: "Bethany Park", email: "bethany@beesweetbakery.com", lat: 30.3075, lng: -97.7378, address: "4500 Duval St, Austin, TX 78751", photoUrl: "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=600&q=80", categoryName: "Desserts & Sweets", categorySlug: "desserts", categoryIcon: "🥧", rating: 4.6, reviewCount: 7, listingCount: 1, hasFreshItems: true, bio: "Vegan and gluten-free cupcakes, cookies, and celebration cakes.", verified: false, state: "TX", city: "Austin" },
  { id: 10, businessName: "Green Gate Growers", name: "Kevin Wu", email: "kevin@greengategrowers.com", lat: 30.2280, lng: -97.8100, address: "6100 W Highway 290, Austin, TX 78735", photoUrl: "https://images.unsplash.com/photo-1523348837708-15d4a09cfac2?w=600&q=80", categoryName: "Fresh Produce", categorySlug: "produce", categoryIcon: "🌽", rating: 4.2, reviewCount: 4, listingCount: 2, hasFreshItems: false, bio: "Microgreens, sprouts, and hydroponic lettuces grown year-round.", verified: true, state: "TX", city: "Austin" },

  // ═══ NASHVILLE, TN (IDs 11–13) ═══
  { id: 11, businessName: "Music City Sourdough", name: "Caroline Baker", email: "caroline@musiccitysourdough.com", lat: 36.1525, lng: -86.7887, address: "500 Church St, Nashville, TN 37203", photoUrl: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&q=80", categoryName: "Bread & Pastries", categorySlug: "bread-pastries", categoryIcon: "🥖", rating: 4.8, reviewCount: 14, listingCount: 3, hasFreshItems: true, bio: "Artisan sourdough with a Nashville twist — our starter is named Dolly. Fresh bread, biscuits, and focaccia daily.", verified: true, state: "TN", city: "Nashville" },
  { id: 12, businessName: "Nashville Honey Co", name: "Marcus Webb", email: "marcus@nashvillehoneyco.com", lat: 36.1100, lng: -86.7700, address: "1200 Laurel St, Nashville, TN 37204", photoUrl: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=600&q=80", categoryName: "Honey & Preserves", categorySlug: "honey-preserves", categoryIcon: "🍯", rating: 4.6, reviewCount: 9, listingCount: 3, hasFreshItems: true, bio: "Urban beekeeping in the heart of Nashville. Raw honey from hives across the city — each neighborhood has its own flavor.", verified: true, state: "TN", city: "Nashville" },
  { id: 13, businessName: "Tennessee Egg Ranch", name: "Will & Annie Cooper", email: "hello@tneggranch.com", lat: 36.1900, lng: -86.7300, address: "2900 Gallatin Pike, Nashville, TN 37206", photoUrl: "https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?w=600&q=80", categoryName: "Eggs & Dairy", categorySlug: "eggs-dairy", categoryIcon: "🥚", rating: 4.9, reviewCount: 11, listingCount: 2, hasFreshItems: true, bio: "Free-range eggs from heritage breed chickens raised on pasture in East Nashville. Bright orange yolks, happy hens.", verified: true, state: "TN", city: "Nashville" },

  // ═══ KNOXVILLE, TN (IDs 14–15) ═══
  { id: 14, businessName: "Volunteer Bakery", name: "Megan Foster", email: "megan@volunteerbakery.com", lat: 35.9606, lng: -83.9207, address: "100 Market Square, Knoxville, TN 37902", photoUrl: "https://images.unsplash.com/photo-1558301211-7099e59b9c58?w=600&q=80", categoryName: "Desserts & Sweets", categorySlug: "desserts", categoryIcon: "🥧", rating: 4.7, reviewCount: 8, listingCount: 3, hasFreshItems: true, bio: "From-scratch cakes, cookies, and tarts made with love in downtown Knoxville. Specializing in Southern classics with a twist.", verified: true, state: "TN", city: "Knoxville" },
  { id: 15, businessName: "Smoky Mountain Farms", name: "Tom & Ruth Hensley", email: "tom@smokymtnfarms.com", lat: 35.9200, lng: -84.0000, address: "4500 Kingston Pike, Knoxville, TN 37919", photoUrl: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=600&q=80", categoryName: "Fresh Produce", categorySlug: "produce", categoryIcon: "🌽", rating: 4.5, reviewCount: 6, listingCount: 3, hasFreshItems: true, bio: "Family farm in the foothills of the Smokies. Seasonal vegetables, mountain berries, and fresh herbs grown naturally.", verified: false, state: "TN", city: "Knoxville" },

  // ═══ CHATTANOOGA, TN (ID 16) ═══
  { id: 16, businessName: "Chattanooga Cookie Co", name: "Jennifer Price", email: "jen@chattcookies.com", lat: 35.0456, lng: -85.3097, address: "200 Broad St, Chattanooga, TN 37402", photoUrl: "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=600&q=80", categoryName: "Desserts & Sweets", categorySlug: "desserts", categoryIcon: "🥧", rating: 4.8, reviewCount: 13, listingCount: 3, hasFreshItems: true, bio: "Gourmet cookies baked fresh every morning — chocolate chip, snickerdoodle, and our famous Chattanooga Caramel Crunch.", verified: true, state: "TN", city: "Chattanooga" },

  // ═══ CHARLOTTE, NC (IDs 17–18) ═══
  { id: 17, businessName: "Queen City Pies", name: "Derrick Mitchell", email: "derrick@queencitypies.com", lat: 35.2271, lng: -80.8431, address: "500 S Tryon St, Charlotte, NC 28202", photoUrl: "https://images.unsplash.com/photo-1535920527002-b35e96722eb9?w=600&q=80", categoryName: "Desserts & Sweets", categorySlug: "desserts", categoryIcon: "🥧", rating: 4.6, reviewCount: 7, listingCount: 2, hasFreshItems: true, bio: "Handmade pies from Uptown Charlotte. Sweet potato, pecan, and seasonal fruit — flaky crust, small-batch goodness.", verified: true, state: "NC", city: "Charlotte" },
  { id: 18, businessName: "CLT Fresh Eggs", name: "Sandra Lee", email: "sandra@cltfresheggs.com", lat: 35.2100, lng: -80.8600, address: "1200 South Blvd, Charlotte, NC 28203", photoUrl: "https://images.unsplash.com/photo-1598965675045-8e1e099edc5c?w=600&q=80", categoryName: "Eggs & Dairy", categorySlug: "eggs-dairy", categoryIcon: "🥚", rating: 4.7, reviewCount: 5, listingCount: 2, hasFreshItems: true, bio: "Backyard eggs from heritage hens in South End. Free-range, soy-free feed, eggs with deep orange yolks.", verified: false, state: "NC", city: "Charlotte" },

  // ═══ RALEIGH, NC (IDs 19–20) ═══
  { id: 19, businessName: "Oak City Bread Co", name: "Ryan O'Neill", email: "ryan@oakcitybread.com", lat: 35.7796, lng: -78.6382, address: "300 Fayetteville St, Raleigh, NC 27601", photoUrl: "https://images.unsplash.com/photo-1549931319-a545799f7b09?w=600&q=80", categoryName: "Bread & Pastries", categorySlug: "bread-pastries", categoryIcon: "🥖", rating: 4.9, reviewCount: 10, listingCount: 3, hasFreshItems: true, bio: "Slow-fermented breads from downtown Raleigh. Our 200-year-old starter makes loaves with character — crusty outside, tender inside.", verified: true, state: "NC", city: "Raleigh" },
  { id: 20, businessName: "Triangle Honey Collective", name: "Angela Cross", email: "angela@trianglehoney.com", lat: 35.7500, lng: -78.7200, address: "4500 Western Blvd, Raleigh, NC 27606", photoUrl: "https://images.unsplash.com/photo-1471943311424-646960669fbc?w=600&q=80", categoryName: "Honey & Preserves", categorySlug: "honey-preserves", categoryIcon: "🍯", rating: 4.4, reviewCount: 4, listingCount: 2, hasFreshItems: false, bio: "A collective of Raleigh-Durham beekeepers. Wildflower, clover, and sourwood honey — raw, unfiltered, local.", verified: false, state: "NC", city: "Raleigh" },

  // ═══ ASHEVILLE, NC (IDs 21–22) ═══
  { id: 21, businessName: "Blue Ridge Bakers", name: "Hannah and Eli Quinn", email: "hello@blueridgebakers.com", lat: 35.5951, lng: -82.5515, address: "50 Broadway St, Asheville, NC 28801", photoUrl: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&q=80", categoryName: "Bread & Pastries", categorySlug: "bread-pastries", categoryIcon: "🥖", rating: 4.8, reviewCount: 14, listingCount: 3, hasFreshItems: true, bio: "Artisan bread bakery in the heart of Asheville. Wood-fired sourdough, rye, and spelt loaves using locally milled flour.", verified: true, state: "NC", city: "Asheville" },
  { id: 22, businessName: "Appalachian Produce", name: "Zachary Cole", email: "zach@appalachianproduce.com", lat: 35.5400, lng: -82.5200, address: "1800 Hendersonville Rd, Asheville, NC 28803", photoUrl: "https://images.unsplash.com/photo-1579113800032-c38bd7635818?w=600&q=80", categoryName: "Fresh Produce", categorySlug: "produce", categoryIcon: "🌽", rating: 4.5, reviewCount: 6, listingCount: 3, hasFreshItems: true, bio: "Mountain-grown organic vegetables from our farm in the Blue Ridge. Heirloom tomatoes, rainbow chard, and sweet corn.", verified: false, state: "NC", city: "Asheville" },

  // ═══ CHARLESTON, SC (IDs 23–24) ═══
  { id: 23, businessName: "Lowcountry Loaves", name: "Catherine Hart", email: "catherine@lowcountryloaves.com", lat: 32.7765, lng: -79.9311, address: "100 Meeting St, Charleston, SC 29401", photoUrl: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&q=80", categoryName: "Bread & Pastries", categorySlug: "bread-pastries", categoryIcon: "🥖", rating: 4.7, reviewCount: 9, listingCount: 3, hasFreshItems: true, bio: "European-style breads with Lowcountry soul. French baguettes, ciabatta, and benne seed loaves baked fresh each morning in downtown Charleston.", verified: true, state: "SC", city: "Charleston" },
  { id: 24, businessName: "Charleston Honey House", name: "George Rivers", email: "george@charlestonhoneyhouse.com", lat: 32.8000, lng: -79.9500, address: "600 Rutledge Ave, Charleston, SC 29403", photoUrl: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=600&q=80", categoryName: "Honey & Preserves", categorySlug: "honey-preserves", categoryIcon: "🍯", rating: 4.6, reviewCount: 7, listingCount: 2, hasFreshItems: true, bio: "Charleston rooftop honey — bees forage on palmetto blossoms and historic gardens. Pure, raw, and full of local flavor.", verified: true, state: "SC", city: "Charleston" },

  // ═══ GREENVILLE, SC (IDs 25–26) ═══
  { id: 25, businessName: "Greenville Growers", name: "Maya Thompson", email: "maya@greenvillegrowers.com", lat: 34.8526, lng: -82.3940, address: "300 Main St, Greenville, SC 29601", photoUrl: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=600&q=80", categoryName: "Fresh Produce", categorySlug: "produce", categoryIcon: "🌽", rating: 4.4, reviewCount: 5, listingCount: 3, hasFreshItems: true, bio: "Upstate South Carolina's urban farm. Microgreens, salad mixes, and seasonal veggies grown sustainably in Greenville.", verified: false, state: "SC", city: "Greenville" },
  { id: 26, businessName: "Palmetto Pastries", name: "Laura Simmons", email: "laura@palmettopastries.com", lat: 34.8200, lng: -82.3200, address: "1500 Woodruff Rd, Greenville, SC 29607", photoUrl: "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=600&q=80", categoryName: "Desserts & Sweets", categorySlug: "desserts", categoryIcon: "🥧", rating: 4.8, reviewCount: 12, listingCount: 2, hasFreshItems: true, bio: "French-inspired pastries from our Greenville home kitchen. Croissants, danishes, and palmiers baked fresh every morning.", verified: true, state: "SC", city: "Greenville" },

  // ═══ COLUMBIA, SC (ID 27) ═══
  { id: 27, businessName: "Soda City Sweets", name: "Kendra Wilson", email: "kendra@sodacitysweets.com", lat: 34.0007, lng: -81.0348, address: "1200 Main St, Columbia, SC 29201", photoUrl: "https://images.unsplash.com/photo-1558301211-7099e59b9c58?w=600&q=80", categoryName: "Desserts & Sweets", categorySlug: "desserts", categoryIcon: "🥧", rating: 4.5, reviewCount: 6, listingCount: 2, hasFreshItems: true, bio: "Columbia's favorite homemade treats — brownies, blondies, and celebration cakes. Made fresh in the heart of Soda City.", verified: false, state: "SC", city: "Columbia" },

  // ═══ RICHMOND, VA (IDs 28–29) ═══
  { id: 28, businessName: "RVA Bread Co", name: "Daniel Harper", email: "daniel@rvabreadco.com", lat: 37.5407, lng: -77.4360, address: "100 E Broad St, Richmond, VA 23219", photoUrl: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&q=80", categoryName: "Bread & Pastries", categorySlug: "bread-pastries", categoryIcon: "🥖", rating: 4.7, reviewCount: 9, listingCount: 3, hasFreshItems: true, bio: "Richmond's neighborhood bakery — sourdough, bagels, and challah made with Virginia-grown grains. Fresh from the oven every morning.", verified: true, state: "VA", city: "Richmond" },
  { id: 29, businessName: "Virginia Egg Co", name: "Karen & Mike Baldwin", email: "karen@virginiaeggco.com", lat: 37.5500, lng: -77.4700, address: "1800 Monument Ave, Richmond, VA 23220", photoUrl: "https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?w=600&q=80", categoryName: "Eggs & Dairy", categorySlug: "eggs-dairy", categoryIcon: "🥚", rating: 4.8, reviewCount: 7, listingCount: 2, hasFreshItems: true, bio: "Pasture-raised eggs from our family farm just outside Richmond. Our hens roam freely on 5 acres — you can taste the difference.", verified: true, state: "VA", city: "Richmond" },

  // ═══ NORFOLK, VA (IDs 30–31) ═══
  { id: 30, businessName: "Coastal Produce", name: "Jamie Torres", email: "jamie@coastalproduceva.com", lat: 36.8468, lng: -76.2859, address: "300 Granby St, Norfolk, VA 23510", photoUrl: "https://images.unsplash.com/photo-1579113800032-c38bd7635818?w=600&q=80", categoryName: "Fresh Produce", categorySlug: "produce", categoryIcon: "🌽", rating: 4.3, reviewCount: 4, listingCount: 2, hasFreshItems: true, bio: "Coastal Virginia's freshest produce — grown in our greenhouse and community garden plots in Norfolk. Seasonal veggies and herbs.", verified: false, state: "VA", city: "Norfolk" },
  { id: 31, businessName: "Mermaid Bakery", name: "Olivia Pierce", email: "olivia@mermaidbakery.com", lat: 36.8700, lng: -76.3000, address: "2500 Colley Ave, Norfolk, VA 23517", photoUrl: "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=600&q=80", categoryName: "Desserts & Sweets", categorySlug: "desserts", categoryIcon: "🥧", rating: 4.6, reviewCount: 8, listingCount: 2, hasFreshItems: true, bio: "Whimsical baked goods from Norfolk's Ghent neighborhood. Cupcakes, macarons, and cookies with coastal-inspired flavors.", verified: true, state: "VA", city: "Norfolk" },

  // ═══ FAYETTEVILLE, AR (IDs 32–33) ═══
  { id: 32, businessName: "Ozark Mountain Honey", name: "Becky Lawrence", email: "becky@ozarkhoney.com", lat: 36.0626, lng: -94.1574, address: "200 Dickson St, Fayetteville, AR 72701", photoUrl: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=600&q=80", categoryName: "Honey & Preserves", categorySlug: "honey-preserves", categoryIcon: "🍯", rating: 4.8, reviewCount: 10, listingCount: 3, hasFreshItems: true, bio: "Pure Ozark honey from hives nestled in the Boston Mountains. Wildflower, blackberry, and persimmon varietals — raw and unfiltered.", verified: true, state: "AR", city: "Fayetteville" },
  { id: 33, businessName: "Razorback Produce", name: "Tim & Sarah Nguyen", email: "tim@razorbackproduce.com", lat: 36.1000, lng: -94.1300, address: "3500 N College Ave, Fayetteville, AR 72703", photoUrl: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=600&q=80", categoryName: "Fresh Produce", categorySlug: "produce", categoryIcon: "🌽", rating: 4.4, reviewCount: 5, listingCount: 2, hasFreshItems: true, bio: "NWA's homegrown vegetables — tomatoes, peppers, squash, and melons from our family plot. No pesticides, just Ozark sunshine.", verified: false, state: "AR", city: "Fayetteville" },

  // ═══ WICHITA, KS (IDs 34–35) ═══
  { id: 34, businessName: "Prairie Flower Bakery", name: "Emily Swanson", email: "emily@prairieflowerbakery.com", lat: 37.6872, lng: -97.3301, address: "100 N Broadway, Wichita, KS 67202", photoUrl: "https://images.unsplash.com/photo-1558301211-7099e59b9c58?w=600&q=80", categoryName: "Desserts & Sweets", categorySlug: "desserts", categoryIcon: "🥧", rating: 4.5, reviewCount: 6, listingCount: 2, hasFreshItems: true, bio: "Kansas prairie-inspired desserts — sunflower seed cookies, wheat berry muffins, and our famous Flint Hills honey cake.", verified: true, state: "KS", city: "Wichita" },
  { id: 35, businessName: "Sunflower State Eggs", name: "Jack and Diane Murray", email: "jack@sunflowerstateeggs.com", lat: 37.7000, lng: -97.2300, address: "8500 E 21st St, Wichita, KS 67206", photoUrl: "https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?w=600&q=80", categoryName: "Eggs & Dairy", categorySlug: "eggs-dairy", categoryIcon: "🥚", rating: 4.9, reviewCount: 15, listingCount: 2, hasFreshItems: true, bio: "Farm-fresh eggs from our Wichita homestead. Free-range hens, no antibiotics, deep golden yolks — the way eggs should taste.", verified: true, state: "KS", city: "Wichita" },
];

// ── Listings ─────────────────────────────────────────────────────────
export const MOCK_LISTINGS: any[] = [
  // ═══ AUSTIN (IDs 1–18) ═══
  { id: 1, title: "Classic Country Loaf", description: "Our signature sourdough — tangy, chewy, with a crackling crust. 800g loaf.", price: 8.5, quantity: 6, photoUrl: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400", dietaryTags: '["vegetarian","vegan"]', vendorName: "ATX Sourdough", vendorId: 1, categoryIcon: "🥖", categorySlug: "bread-pastries", postType: "baked_today", postedAt: minsAgo(25), pickupWindowStart: pickupToday(7), pickupWindowEnd: pickupToday(14), city: "Austin", state: "TX" },
  { id: 2, title: "Cinnamon Raisin Swirl", description: "Sourdough with organic cinnamon and plump California raisins.", price: 10.0, quantity: 4, photoUrl: "https://images.unsplash.com/photo-1509365465985-25d11c17e812?w=400", dietaryTags: '["vegetarian"]', vendorName: "ATX Sourdough", vendorId: 1, categoryIcon: "🥖", categorySlug: "bread-pastries", postType: "baked_today", postedAt: hoursAgo(1.5), pickupWindowStart: pickupToday(7), pickupWindowEnd: pickupToday(14), city: "Austin", state: "TX" },
  { id: 3, title: "Everything Bagel Sourdough", description: "Limited batch — sourdough rolled in house-made everything seasoning.", price: 9.5, quantity: 2, photoUrl: "https://images.unsplash.com/photo-1549931319-a545799f7b09?w=400", dietaryTags: '["vegetarian"]', vendorName: "ATX Sourdough", vendorId: 1, categoryIcon: "🥖", categorySlug: "bread-pastries", postType: "limited_batch", postedAt: hoursAgo(3), pickupWindowStart: pickupToday(7), pickupWindowEnd: pickupToday(14), city: "Austin", state: "TX" },
  { id: 4, title: "Farm Fresh Dozen", description: "One dozen free-range eggs from pastured hens. Rich orange yolks.", price: 7.0, quantity: 20, photoUrl: "https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?w=400", dietaryTags: '["vegetarian","gluten-free"]', vendorName: "Eastside Eggs", vendorId: 2, categoryIcon: "🥚", categorySlug: "eggs-dairy", postType: "available_now", postedAt: minsAgo(15), pickupWindowStart: pickupToday(8), pickupWindowEnd: pickupToday(18), city: "Austin", state: "TX" },
  { id: 5, title: "Half Dozen + Herbs", description: "6 eggs plus a bundle of fresh kitchen herbs from our garden.", price: 6.0, quantity: 10, photoUrl: "https://images.unsplash.com/photo-1598965675045-8e1e099edc5c?w=400", dietaryTags: '["vegetarian","gluten-free"]', vendorName: "Eastside Eggs", vendorId: 2, categoryIcon: "🥚", categorySlug: "eggs-dairy", postType: "available_now", postedAt: hoursAgo(2), pickupWindowStart: pickupToday(8), pickupWindowEnd: pickupToday(18), city: "Austin", state: "TX" },
  { id: 6, title: "Wildflower Honey — 16oz", description: "Raw, unfiltered wildflower honey from spring blooms. Light, floral, never heated.", price: 14.0, quantity: 15, photoUrl: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=400", dietaryTags: '["gluten-free"]', vendorName: "Hill Country Honey", vendorId: 3, categoryIcon: "🍯", categorySlug: "honey-preserves", postType: "available_now", postedAt: hoursAgo(5), pickupWindowStart: pickupToday(9), pickupWindowEnd: pickupToday(17), city: "Austin", state: "TX" },
  { id: 7, title: "Mesquite Honey — 8oz", description: "Dark, bold honey from mesquite blossoms. Smoky-sweet, perfect for BBQ glaze.", price: 10.0, quantity: 8, photoUrl: "https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=400", dietaryTags: '["gluten-free"]', vendorName: "Hill Country Honey", vendorId: 3, categoryIcon: "🍯", categorySlug: "honey-preserves", postType: "available_now", postedAt: hoursAgo(8), pickupWindowStart: pickupToday(9), pickupWindowEnd: pickupToday(17), city: "Austin", state: "TX" },
  { id: 8, title: "Honeycomb Square", description: "A square of raw honeycomb — wax and honey together. Amazing on cheese boards.", price: 8.0, quantity: 3, photoUrl: "https://images.unsplash.com/photo-1471943311424-646960669fbc?w=400", dietaryTags: '["gluten-free"]', vendorName: "Hill Country Honey", vendorId: 3, categoryIcon: "🍯", categorySlug: "honey-preserves", postType: "available_now", postedAt: hoursAgo(28), pickupWindowStart: pickupToday(9), pickupWindowEnd: pickupToday(17), city: "Austin", state: "TX" },
  { id: 9, title: "Texas Pecan Pie", description: "Our blue-ribbon pecan pie with Texas pecans in a buttery, flaky crust. 9-inch.", price: 28.0, quantity: 3, photoUrl: "https://images.unsplash.com/photo-1535920527002-b35e96722eb9?w=400", dietaryTags: '["vegetarian"]', vendorName: "Texas Pie Company", vendorId: 4, categoryIcon: "🥧", categorySlug: "desserts", postType: "just_made", postedAt: minsAgo(45), pickupWindowStart: pickupToday(10), pickupWindowEnd: pickupToday(17), city: "Austin", state: "TX" },
  { id: 10, title: "Seasonal Fruit Pie", description: "Summer peach and berry pie with a lattice top. Made with Fredericksburg peaches.", price: 26.0, quantity: 2, photoUrl: "https://images.unsplash.com/photo-1568571780765-9276ac2c48c9?w=400", dietaryTags: '["vegetarian"]', vendorName: "Texas Pie Company", vendorId: 4, categoryIcon: "🥧", categorySlug: "desserts", postType: "just_made", postedAt: hoursAgo(6), pickupWindowStart: pickupToday(10), pickupWindowEnd: pickupToday(17), city: "Austin", state: "TX" },
  { id: 11, title: "Weekly Veggie Box", description: "A curated box of seasonal organic vegetables — tomatoes, zucchini, basil, bell peppers, and salad greens.", price: 25.0, quantity: 8, photoUrl: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=400", dietaryTags: '["vegan","gluten-free"]', vendorName: "Sunset Farms Produce", vendorId: 5, categoryIcon: "🌽", categorySlug: "produce", postType: "harvested_today", postedAt: minsAgo(10), pickupWindowStart: pickupToday(8), pickupWindowEnd: pickupToday(19), city: "Austin", state: "TX" },
  { id: 12, title: "Heirloom Tomato Basket", description: "5 lbs of mixed heirloom tomatoes — Cherokee Purple, Brandywine, Sun Gold cherries.", price: 15.0, quantity: 5, photoUrl: "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=400", dietaryTags: '["vegan","gluten-free"]', vendorName: "Sunset Farms Produce", vendorId: 5, categoryIcon: "🌽", categorySlug: "produce", postType: "harvested_today", postedAt: hoursAgo(4), pickupWindowStart: pickupToday(8), pickupWindowEnd: pickupToday(19), city: "Austin", state: "TX" },
  { id: 13, title: "Herb Bundle", description: "Fresh-cut basil, cilantro, rosemary, and mint from our garden.", price: 6.0, quantity: 12, photoUrl: "https://images.unsplash.com/photo-1600852659773-7e5a02b35c5a?w=400", dietaryTags: '["vegan","gluten-free"]', vendorName: "Sunset Farms Produce", vendorId: 5, categoryIcon: "🌽", categorySlug: "produce", postType: "harvested_today", postedAt: hoursAgo(12), pickupWindowStart: pickupToday(8), pickupWindowEnd: pickupToday(19), city: "Austin", state: "TX" },
  { id: 14, title: "Spring Bouquet", description: "A hand-tied bouquet of seasonal blooms from our farm.", price: 18.0, quantity: 4, photoUrl: "https://images.unsplash.com/photo-1487530811176-3780de880c2d?w=400", dietaryTags: '[]', vendorName: "Flower Child Farms", vendorId: 6, categoryIcon: "🌼", categorySlug: "flowers", postType: "available_now", postedAt: minsAgo(30), pickupWindowStart: pickupToday(9), pickupWindowEnd: pickupToday(16), city: "Austin", state: "TX" },
  { id: 15, title: "Migas Taco Plate", description: "3 migas tacos with chips and salsa — the Austin classic.", price: 9.5, quantity: 10, photoUrl: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=400", dietaryTags: '["vegetarian"]', vendorName: "Taco Tones", vendorId: 7, categoryIcon: "🚚", categorySlug: "food-truck", postType: "available_now", postedAt: hoursAgo(1), pickupWindowStart: pickupToday(7), pickupWindowEnd: pickupToday(14), city: "Austin", state: "TX" },
  { id: 16, title: "Family Lasagna", description: "A full tray of classic meat lasagna — feeds 6.", price: 32.0, quantity: 1, photoUrl: "https://images.unsplash.com/photo-1556911220-bff31c812dba?w=400", dietaryTags: '[]', vendorName: "Mama Lu's Kitchen", vendorId: 8, categoryIcon: "🍽️", categorySlug: "meals", postType: "available_now", postedAt: hoursAgo(26), pickupWindowStart: pickupToday(12), pickupWindowEnd: pickupToday(20), city: "Austin", state: "TX" },
  { id: 17, title: "Vegan Cupcake Box (6)", description: "Assorted vegan cupcakes — chocolate, vanilla, and red velvet.", price: 22.0, quantity: 3, photoUrl: "https://images.unsplash.com/photo-1558301211-7099e59b9c58?w=400", dietaryTags: '["vegan","gluten-free"]', vendorName: "Bee Sweet Bakery", vendorId: 9, categoryIcon: "🥧", categorySlug: "desserts", postType: "just_made", postedAt: hoursAgo(3.5), pickupWindowStart: pickupToday(11), pickupWindowEnd: pickupToday(17), city: "Austin", state: "TX" },
  { id: 18, title: "Microgreens Sampler", description: "3 trays of sunflower, pea shoots, and radish microgreens.", price: 15.0, quantity: 5, photoUrl: "https://images.unsplash.com/photo-1500076656116-558758c991c1?w=400", dietaryTags: '["vegan","gluten-free"]', vendorName: "Green Gate Growers", vendorId: 10, categoryIcon: "🌽", categorySlug: "produce", postType: "harvested_today", postedAt: hoursAgo(22), pickupWindowStart: pickupToday(10), pickupWindowEnd: pickupToday(15), city: "Austin", state: "TX" },

  // ═══ NASHVILLE (IDs 19–27) ═══
  { id: 19, title: "Dolly's Country Loaf", description: "Our signature sourdough named after Nashville's queen. Tangy, airy crumb, crackling crust.", price: 9.0, quantity: 5, photoUrl: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400", dietaryTags: '["vegetarian","vegan"]', vendorName: "Music City Sourdough", vendorId: 11, categoryIcon: "🥖", categorySlug: "bread-pastries", postType: "baked_today", postedAt: minsAgo(40), pickupWindowStart: pickupToday(7), pickupWindowEnd: pickupToday(13), city: "Nashville", state: "TN" },
  { id: 20, title: "Biscuit Box (6)", description: "Six buttermilk biscuits — tall, flaky, and ready for your jam.", price: 12.0, quantity: 8, photoUrl: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400", dietaryTags: '["vegetarian"]', vendorName: "Music City Sourdough", vendorId: 11, categoryIcon: "🥖", categorySlug: "bread-pastries", postType: "baked_today", postedAt: hoursAgo(2), pickupWindowStart: pickupToday(7), pickupWindowEnd: pickupToday(13), city: "Nashville", state: "TN" },
  { id: 21, title: "Focaccia Garden", description: "Rosemary and sea salt focaccia with cherry tomatoes pressed into the top.", price: 11.0, quantity: 4, photoUrl: "https://images.unsplash.com/photo-1549931319-a545799f7b09?w=400", dietaryTags: '["vegan"]', vendorName: "Music City Sourdough", vendorId: 11, categoryIcon: "🥖", categorySlug: "bread-pastries", postType: "baked_today", postedAt: hoursAgo(5), pickupWindowStart: pickupToday(7), pickupWindowEnd: pickupToday(13), city: "Nashville", state: "TN" },
  { id: 22, title: "East Nashville Wildflower — 12oz", description: "Raw honey from our East Nashville hives. Floral, delicate, and never heated.", price: 12.0, quantity: 10, photoUrl: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=400", dietaryTags: '["gluten-free"]', vendorName: "Nashville Honey Co", vendorId: 12, categoryIcon: "🍯", categorySlug: "honey-preserves", postType: "available_now", postedAt: minsAgo(55), pickupWindowStart: pickupToday(9), pickupWindowEnd: pickupToday(17), city: "Nashville", state: "TN" },
  { id: 23, title: "Germantown Clover Honey — 8oz", description: "Light, sweet clover honey from our historic Germantown apiary.", price: 9.0, quantity: 6, photoUrl: "https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=400", dietaryTags: '["gluten-free"]', vendorName: "Nashville Honey Co", vendorId: 12, categoryIcon: "🍯", categorySlug: "honey-preserves", postType: "available_now", postedAt: hoursAgo(7), pickupWindowStart: pickupToday(9), pickupWindowEnd: pickupToday(17), city: "Nashville", state: "TN" },
  { id: 24, title: "Honey & Comb Sampler", description: "An 8oz jar of wildflower honey with a chunk of raw comb inside.", price: 14.0, quantity: 4, photoUrl: "https://images.unsplash.com/photo-1471943311424-646960669fbc?w=400", dietaryTags: '["gluten-free"]', vendorName: "Nashville Honey Co", vendorId: 12, categoryIcon: "🍯", categorySlug: "honey-preserves", postType: "available_now", postedAt: daysAgo(1), pickupWindowStart: pickupToday(9), pickupWindowEnd: pickupToday(17), city: "Nashville", state: "TN" },
  { id: 25, title: "Heritage Dozen", description: "One dozen eggs from our heritage breed hens — Araucanas and Rhode Island Reds.", price: 8.0, quantity: 12, photoUrl: "https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?w=400", dietaryTags: '["vegetarian","gluten-free"]', vendorName: "Tennessee Egg Ranch", vendorId: 13, categoryIcon: "🥚", categorySlug: "eggs-dairy", postType: "available_now", postedAt: minsAgo(30), pickupWindowStart: pickupToday(8), pickupWindowEnd: pickupToday(18), city: "Nashville", state: "TN" },
  { id: 26, title: "Egg & Herb Breakfast Box", description: "6 eggs, fresh chives, and a small jar of herb salt — everything for the perfect scramble.", price: 10.0, quantity: 8, photoUrl: "https://images.unsplash.com/photo-1598965675045-8e1e099edc5c?w=400", dietaryTags: '["vegetarian","gluten-free"]', vendorName: "Tennessee Egg Ranch", vendorId: 13, categoryIcon: "🥚", categorySlug: "eggs-dairy", postType: "available_now", postedAt: hoursAgo(4), pickupWindowStart: pickupToday(8), pickupWindowEnd: pickupToday(18), city: "Nashville", state: "TN" },

  // ═══ KNOXVILLE (IDs 27–32) ═══
  { id: 27, title: "Tennessee Whiskey Cake", description: "A rich bundt cake made with Tennessee whiskey, brown sugar, and pecans.", price: 28.0, quantity: 3, photoUrl: "https://images.unsplash.com/photo-1558301211-7099e59b9c58?w=400", dietaryTags: '["vegetarian"]', vendorName: "Volunteer Bakery", vendorId: 14, categoryIcon: "🥧", categorySlug: "desserts", postType: "just_made", postedAt: minsAgo(20), pickupWindowStart: pickupToday(11), pickupWindowEnd: pickupToday(17), city: "Knoxville", state: "TN" },
  { id: 28, title: "Cookie Box (12)", description: "A dozen assorted cookies — chocolate chip, oatmeal raisin, and snickerdoodle.", price: 18.0, quantity: 6, photoUrl: "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=400", dietaryTags: '["vegetarian"]', vendorName: "Volunteer Bakery", vendorId: 14, categoryIcon: "🥧", categorySlug: "desserts", postType: "just_made", postedAt: hoursAgo(3), pickupWindowStart: pickupToday(11), pickupWindowEnd: pickupToday(17), city: "Knoxville", state: "TN" },
  { id: 29, title: "Key Lime Tart", description: "Creamy key lime tart with a graham cracker crust. Bright, tangy, and refreshing.", price: 16.0, quantity: 4, photoUrl: "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400", dietaryTags: '["vegetarian"]', vendorName: "Volunteer Bakery", vendorId: 14, categoryIcon: "🥧", categorySlug: "desserts", postType: "just_made", postedAt: hoursAgo(8), pickupWindowStart: pickupToday(11), pickupWindowEnd: pickupToday(17), city: "Knoxville", state: "TN" },
  { id: 30, title: "Mountain Berry Basket", description: "A mixed basket of seasonal berries — blueberries, blackberries, and raspberries from our Smoky Mountain fields.", price: 12.0, quantity: 8, photoUrl: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=400", dietaryTags: '["vegan","gluten-free","organic"]', vendorName: "Smoky Mountain Farms", vendorId: 15, categoryIcon: "🌽", categorySlug: "produce", postType: "harvested_today", postedAt: minsAgo(15), pickupWindowStart: pickupToday(9), pickupWindowEnd: pickupToday(16), city: "Knoxville", state: "TN" },
  { id: 31, title: "Farm Veggie Box", description: "A curated box of seasonal vegetables — tomatoes, squash, green beans, and sweet corn.", price: 22.0, quantity: 6, photoUrl: "https://images.unsplash.com/photo-1579113800032-c38bd7635818?w=400", dietaryTags: '["vegan","gluten-free"]', vendorName: "Smoky Mountain Farms", vendorId: 15, categoryIcon: "🌽", categorySlug: "produce", postType: "harvested_today", postedAt: hoursAgo(2), pickupWindowStart: pickupToday(9), pickupWindowEnd: pickupToday(16), city: "Knoxville", state: "TN" },
  { id: 32, title: "Herb Garden Bundle", description: "Fresh-cut basil, rosemary, thyme, and sage from our mountain garden.", price: 5.0, quantity: 10, photoUrl: "https://images.unsplash.com/photo-1600852659773-7e5a02b35c5a?w=400", dietaryTags: '["vegan","gluten-free"]', vendorName: "Smoky Mountain Farms", vendorId: 15, categoryIcon: "🌽", categorySlug: "produce", postType: "harvested_today", postedAt: hoursAgo(6), pickupWindowStart: pickupToday(9), pickupWindowEnd: pickupToday(16), city: "Knoxville", state: "TN" },

  // ═══ CHATTANOOGA (IDs 33–35) ═══
  { id: 33, title: "Chattanooga Caramel Crunch (6)", description: "Our signature cookie — brown butter caramel, dark chocolate, and a sprinkle of sea salt.", price: 15.0, quantity: 8, photoUrl: "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=400", dietaryTags: '["vegetarian"]', vendorName: "Chattanooga Cookie Co", vendorId: 16, categoryIcon: "🥧", categorySlug: "desserts", postType: "baked_today", postedAt: minsAgo(10), pickupWindowStart: pickupToday(10), pickupWindowEnd: pickupToday(16), city: "Chattanooga", state: "TN" },
  { id: 34, title: "Snickerdoodle Dozen", description: "A dozen snickerdoodles — soft in the middle, crispy edges, rolled in cinnamon sugar.", price: 14.0, quantity: 6, photoUrl: "https://images.unsplash.com/photo-1558301211-7099e59b9c58?w=400", dietaryTags: '["vegetarian"]', vendorName: "Chattanooga Cookie Co", vendorId: 16, categoryIcon: "🥧", categorySlug: "desserts", postType: "baked_today", postedAt: hoursAgo(2.5), pickupWindowStart: pickupToday(10), pickupWindowEnd: pickupToday(16), city: "Chattanooga", state: "TN" },
  { id: 35, title: "Cookie Sampler Box", description: "6 of each: Caramel Crunch, Snickerdoodle, and Double Chocolate. A Chattanooga favorite.", price: 22.0, quantity: 5, photoUrl: "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400", dietaryTags: '["vegetarian"]', vendorName: "Chattanooga Cookie Co", vendorId: 16, categoryIcon: "🥧", categorySlug: "desserts", postType: "limited_batch", postedAt: hoursAgo(5), pickupWindowStart: pickupToday(10), pickupWindowEnd: pickupToday(16), city: "Chattanooga", state: "TN" },

  // ═══ CHARLOTTE (IDs 36–39) ═══
  { id: 36, title: "Sweet Potato Pie", description: "Velvety North Carolina sweet potato pie with a flaky butter crust.", price: 24.0, quantity: 4, photoUrl: "https://images.unsplash.com/photo-1535920527002-b35e96722eb9?w=400", dietaryTags: '["vegetarian"]', vendorName: "Queen City Pies", vendorId: 17, categoryIcon: "🥧", categorySlug: "desserts", postType: "just_made", postedAt: minsAgo(35), pickupWindowStart: pickupToday(10), pickupWindowEnd: pickupToday(17), city: "Charlotte", state: "NC" },
  { id: 37, title: "NC Pecan Pie", description: "Classic pecan pie made with North Carolina pecans and a touch of bourbon.", price: 26.0, quantity: 3, photoUrl: "https://images.unsplash.com/photo-1568571780765-9276ac2c48c9?w=400", dietaryTags: '["vegetarian"]', vendorName: "Queen City Pies", vendorId: 17, categoryIcon: "🥧", categorySlug: "desserts", postType: "just_made", postedAt: hoursAgo(4), pickupWindowStart: pickupToday(10), pickupWindowEnd: pickupToday(17), city: "Charlotte", state: "NC" },
  { id: 38, title: "Heritage Hen Dozen", description: "One dozen eggs from heritage breed hens in South End. Deep orange yolks.", price: 7.5, quantity: 10, photoUrl: "https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?w=400", dietaryTags: '["vegetarian","gluten-free"]', vendorName: "CLT Fresh Eggs", vendorId: 18, categoryIcon: "🥚", categorySlug: "eggs-dairy", postType: "available_now", postedAt: minsAgo(20), pickupWindowStart: pickupToday(8), pickupWindowEnd: pickupToday(18), city: "Charlotte", state: "NC" },
  { id: 39, title: "Half Dozen + Microgreens", description: "6 eggs with a tray of sunflower microgreens from our garden.", price: 9.0, quantity: 8, photoUrl: "https://images.unsplash.com/photo-1598965675045-8e1e099edc5c?w=400", dietaryTags: '["vegetarian","gluten-free"]', vendorName: "CLT Fresh Eggs", vendorId: 18, categoryIcon: "🥚", categorySlug: "eggs-dairy", postType: "available_now", postedAt: hoursAgo(5), pickupWindowStart: pickupToday(8), pickupWindowEnd: pickupToday(18), city: "Charlotte", state: "NC" },

  // ═══ RALEIGH (IDs 40–44) ═══
  { id: 40, title: "Oak City Miche", description: "A large rustic sourdough miche — nutty, hearty, and perfect for sandwiches.", price: 10.0, quantity: 5, photoUrl: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400", dietaryTags: '["vegetarian","vegan"]', vendorName: "Oak City Bread Co", vendorId: 19, categoryIcon: "🥖", categorySlug: "bread-pastries", postType: "baked_today", postedAt: minsAgo(30), pickupWindowStart: pickupToday(7), pickupWindowEnd: pickupToday(14), city: "Raleigh", state: "NC" },
  { id: 41, title: "Sesame Semolina Loaf", description: "Golden semolina bread with toasted sesame crust. Slightly sweet, great with soup.", price: 9.0, quantity: 4, photoUrl: "https://images.unsplash.com/photo-1549931319-a545799f7b09?w=400", dietaryTags: '["vegetarian","vegan"]', vendorName: "Oak City Bread Co", vendorId: 19, categoryIcon: "🥖", categorySlug: "bread-pastries", postType: "baked_today", postedAt: hoursAgo(1.5), pickupWindowStart: pickupToday(7), pickupWindowEnd: pickupToday(14), city: "Raleigh", state: "NC" },
  { id: 42, title: "Cinnamon Babka", description: "Rich, twisted babka with cinnamon-walnut filling. Perfect for brunch.", price: 14.0, quantity: 3, photoUrl: "https://images.unsplash.com/photo-1509365465985-25d11c17e812?w=400", dietaryTags: '["vegetarian"]', vendorName: "Oak City Bread Co", vendorId: 19, categoryIcon: "🥖", categorySlug: "bread-pastries", postType: "limited_batch", postedAt: hoursAgo(4), pickupWindowStart: pickupToday(7), pickupWindowEnd: pickupToday(14), city: "Raleigh", state: "NC" },
  { id: 43, title: "Triangle Wildflower Honey — 16oz", description: "A blend from hives across Raleigh, Durham, and Chapel Hill. Complex and floral.", price: 13.0, quantity: 8, photoUrl: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=400", dietaryTags: '["gluten-free"]', vendorName: "Triangle Honey Collective", vendorId: 20, categoryIcon: "🍯", categorySlug: "honey-preserves", postType: "available_now", postedAt: minsAgo(50), pickupWindowStart: pickupToday(10), pickupWindowEnd: pickupToday(16), city: "Raleigh", state: "NC" },
  { id: 44, title: "Sourwood Honey — 8oz", description: "Rare sourwood honey from the NC mountains. Buttery, spicy, prized by honey lovers.", price: 16.0, quantity: 3, photoUrl: "https://images.unsplash.com/photo-1471943311424-646960669fbc?w=400", dietaryTags: '["gluten-free"]', vendorName: "Triangle Honey Collective", vendorId: 20, categoryIcon: "🍯", categorySlug: "honey-preserves", postType: "limited_batch", postedAt: daysAgo(2), pickupWindowStart: pickupToday(10), pickupWindowEnd: pickupToday(16), city: "Raleigh", state: "NC" },

  // ═══ ASHEVILLE (IDs 45–49) ═══
  { id: 45, title: "Wood-Fired Country Loaf", description: "Sourdough baked in our outdoor wood-fired oven. Smoky, complex, and incredibly crusty.", price: 10.0, quantity: 5, photoUrl: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400", dietaryTags: '["vegan"]', vendorName: "Blue Ridge Bakers", vendorId: 21, categoryIcon: "🥖", categorySlug: "bread-pastries", postType: "baked_today", postedAt: minsAgo(15), pickupWindowStart: pickupToday(8), pickupWindowEnd: pickupToday(13), city: "Asheville", state: "NC" },
  { id: 46, title: "Mountain Rye", description: "Hearty 50% rye sourdough with caraway seeds. Dense, flavorful, old-world style.", price: 9.0, quantity: 4, photoUrl: "https://images.unsplash.com/photo-1549931319-a545799f7b09?w=400", dietaryTags: '["vegan"]', vendorName: "Blue Ridge Bakers", vendorId: 21, categoryIcon: "🥖", categorySlug: "bread-pastries", postType: "baked_today", postedAt: hoursAgo(2), pickupWindowStart: pickupToday(8), pickupWindowEnd: pickupToday(13), city: "Asheville", state: "NC" },
  { id: 47, title: "Spelt Baguette (2)", description: "Two spelt flour baguettes — nutty, crisp, and digestible. A Blue Ridge favorite.", price: 8.0, quantity: 6, photoUrl: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400", dietaryTags: '["vegan"]', vendorName: "Blue Ridge Bakers", vendorId: 21, categoryIcon: "🥖", categorySlug: "bread-pastries", postType: "baked_today", postedAt: hoursAgo(5), pickupWindowStart: pickupToday(8), pickupWindowEnd: pickupToday(13), city: "Asheville", state: "NC" },
  { id: 48, title: "Heirloom Tomato Box", description: "5 lbs of mixed heirloom tomatoes — Brandywine, Cherokee Purple, and Sun Gold from our mountain garden.", price: 16.0, quantity: 6, photoUrl: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=400", dietaryTags: '["vegan","gluten-free","organic"]', vendorName: "Appalachian Produce", vendorId: 22, categoryIcon: "🌽", categorySlug: "produce", postType: "harvested_today", postedAt: minsAgo(25), pickupWindowStart: pickupToday(9), pickupWindowEnd: pickupToday(17), city: "Asheville", state: "NC" },
  { id: 49, title: "Rainbow Chard & Kale Bundle", description: "A big bundle of organic rainbow chard and lacinato kale from our mountain fields.", price: 7.0, quantity: 10, photoUrl: "https://images.unsplash.com/photo-1579113800032-c38bd7635818?w=400", dietaryTags: '["vegan","gluten-free","organic"]', vendorName: "Appalachian Produce", vendorId: 22, categoryIcon: "🌽", categorySlug: "produce", postType: "harvested_today", postedAt: hoursAgo(3), pickupWindowStart: pickupToday(9), pickupWindowEnd: pickupToday(17), city: "Asheville", state: "NC" },
  { id: 50, title: "Sweet Corn (6 ears)", description: "Just-picked sweet corn from our Blue Ridge plot. Incredibly sweet and tender.", price: 8.0, quantity: 12, photoUrl: "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=400", dietaryTags: '["vegan","gluten-free"]', vendorName: "Appalachian Produce", vendorId: 22, categoryIcon: "🌽", categorySlug: "produce", postType: "harvested_today", postedAt: hoursAgo(7), pickupWindowStart: pickupToday(9), pickupWindowEnd: pickupToday(17), city: "Asheville", state: "NC" },

  // ═══ CHARLESTON (IDs 51–55) ═══
  { id: 51, title: "Charleston Benne Seed Loaf", description: "Sourdough with toasted benne (sesame) seeds — nutty, aromatic, an heirloom Lowcountry grain.", price: 9.5, quantity: 5, photoUrl: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400", dietaryTags: '["vegan"]', vendorName: "Lowcountry Loaves", vendorId: 23, categoryIcon: "🥖", categorySlug: "bread-pastries", postType: "baked_today", postedAt: minsAgo(20), pickupWindowStart: pickupToday(7), pickupWindowEnd: pickupToday(13), city: "Charleston", state: "SC" },
  { id: 52, title: "French Baguette (2)", description: "Two classic French baguettes — thin, crispy, with an airy crumb. Baked at dawn.", price: 7.0, quantity: 8, photoUrl: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400", dietaryTags: '["vegan"]', vendorName: "Lowcountry Loaves", vendorId: 23, categoryIcon: "🥖", categorySlug: "bread-pastries", postType: "baked_today", postedAt: hoursAgo(1), pickupWindowStart: pickupToday(7), pickupWindowEnd: pickupToday(13), city: "Charleston", state: "SC" },
  { id: 53, title: "Ciabatta (2)", description: "Two rustic Italian ciabatta loaves — open crumb, perfect for sandwiches and bruschetta.", price: 8.5, quantity: 6, photoUrl: "https://images.unsplash.com/photo-1549931319-a545799f7b09?w=400", dietaryTags: '["vegan"]', vendorName: "Lowcountry Loaves", vendorId: 23, categoryIcon: "🥖", categorySlug: "bread-pastries", postType: "baked_today", postedAt: hoursAgo(3.5), pickupWindowStart: pickupToday(7), pickupWindowEnd: pickupToday(13), city: "Charleston", state: "SC" },
  { id: 54, title: "Palmetto Blossom Honey — 12oz", description: "Light, floral honey from bees that forage on palmetto blossoms in historic Charleston gardens.", price: 13.0, quantity: 8, photoUrl: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=400", dietaryTags: '["gluten-free"]', vendorName: "Charleston Honey House", vendorId: 24, categoryIcon: "🍯", categorySlug: "honey-preserves", postType: "available_now", postedAt: minsAgo(45), pickupWindowStart: pickupToday(10), pickupWindowEnd: pickupToday(16), city: "Charleston", state: "SC" },
  { id: 55, title: "Historic District Comb Honey", description: "A wedge of raw honeycomb from our King Street hives — the purest way to experience Charleston honey.", price: 11.0, quantity: 4, photoUrl: "https://images.unsplash.com/photo-1471943311424-646960669fbc?w=400", dietaryTags: '["gluten-free"]', vendorName: "Charleston Honey House", vendorId: 24, categoryIcon: "🍯", categorySlug: "honey-preserves", postType: "limited_batch", postedAt: daysAgo(1), pickupWindowStart: pickupToday(10), pickupWindowEnd: pickupToday(16), city: "Charleston", state: "SC" },

  // ═══ GREENVILLE (IDs 56–60) ═══
  { id: 56, title: "Microgreens Sampler", description: "3 trays of sunflower, pea shoots, and radish microgreens. Packed with flavor and nutrients.", price: 14.0, quantity: 6, photoUrl: "https://images.unsplash.com/photo-1523348837708-15d4a09cfac2?w=400", dietaryTags: '["vegan","gluten-free","keto"]', vendorName: "Greenville Growers", vendorId: 25, categoryIcon: "🌽", categorySlug: "produce", postType: "harvested_today", postedAt: minsAgo(18), pickupWindowStart: pickupToday(9), pickupWindowEnd: pickupToday(16), city: "Greenville", state: "SC" },
  { id: 57, title: "Salad Greens Box", description: "A mix of baby lettuce, arugula, and spinach — enough salads for the week.", price: 10.0, quantity: 8, photoUrl: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=400", dietaryTags: '["vegan","gluten-free","organic"]', vendorName: "Greenville Growers", vendorId: 25, categoryIcon: "🌽", categorySlug: "produce", postType: "harvested_today", postedAt: hoursAgo(2), pickupWindowStart: pickupToday(9), pickupWindowEnd: pickupToday(16), city: "Greenville", state: "SC" },
  { id: 58, title: "Seasonal Veggie Bag", description: "A bag of whatever's best today — squash, peppers, eggplant, and tomatoes from our urban farm.", price: 18.0, quantity: 5, photoUrl: "https://images.unsplash.com/photo-1579113800032-c38bd7635818?w=400", dietaryTags: '["vegan","gluten-free"]', vendorName: "Greenville Growers", vendorId: 25, categoryIcon: "🌽", categorySlug: "produce", postType: "harvested_today", postedAt: hoursAgo(5), pickupWindowStart: pickupToday(9), pickupWindowEnd: pickupToday(16), city: "Greenville", state: "SC" },
  { id: 59, title: "Croissant Box (4)", description: "Four flaky butter croissants — golden, layered, and baked fresh at dawn.", price: 14.0, quantity: 6, photoUrl: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400", dietaryTags: '["vegetarian"]', vendorName: "Palmetto Pastries", vendorId: 26, categoryIcon: "🥧", categorySlug: "desserts", postType: "baked_today", postedAt: minsAgo(12), pickupWindowStart: pickupToday(8), pickupWindowEnd: pickupToday(14), city: "Greenville", state: "SC" },
  { id: 60, title: "Pain au Chocolat (4)", description: "Four chocolate croissants with dark French chocolate batons. Warm them up for breakfast heaven.", price: 16.0, quantity: 5, photoUrl: "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400", dietaryTags: '["vegetarian"]', vendorName: "Palmetto Pastries", vendorId: 26, categoryIcon: "🥧", categorySlug: "desserts", postType: "baked_today", postedAt: hoursAgo(2.5), pickupWindowStart: pickupToday(8), pickupWindowEnd: pickupToday(14), city: "Greenville", state: "SC" },

  // ═══ COLUMBIA (IDs 61–62) ═══
  { id: 61, title: "Soda City Brownie Box (6)", description: "Six fudgy brownies — classic, walnut, and cream cheese swirl. The Soda City staple.", price: 16.0, quantity: 7, photoUrl: "https://images.unsplash.com/photo-1558301211-7099e59b9c58?w=400", dietaryTags: '["vegetarian"]', vendorName: "Soda City Sweets", vendorId: 27, categoryIcon: "🥧", categorySlug: "desserts", postType: "just_made", postedAt: minsAgo(28), pickupWindowStart: pickupToday(10), pickupWindowEnd: pickupToday(16), city: "Columbia", state: "SC" },
  { id: 62, title: "Celebration Cake (8-inch)", description: "A classic layer cake with buttercream frosting. Chocolate or vanilla — your choice. Perfect for birthdays.", price: 35.0, quantity: 2, photoUrl: "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400", dietaryTags: '["vegetarian"]', vendorName: "Soda City Sweets", vendorId: 27, categoryIcon: "🥧", categorySlug: "desserts", postType: "just_made", postedAt: hoursAgo(6), pickupWindowStart: pickupToday(10), pickupWindowEnd: pickupToday(16), city: "Columbia", state: "SC" },

  // ═══ RICHMOND (IDs 63–67) ═══
  { id: 63, title: "River City Sourdough", description: "Our classic sourdough loaf made with Virginia-grown wheat. Tangy, rustic, beautiful crumb.", price: 9.0, quantity: 6, photoUrl: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400", dietaryTags: '["vegan"]', vendorName: "RVA Bread Co", vendorId: 28, categoryIcon: "🥖", categorySlug: "bread-pastries", postType: "baked_today", postedAt: minsAgo(22), pickupWindowStart: pickupToday(7), pickupWindowEnd: pickupToday(13), city: "Richmond", state: "VA" },
  { id: 64, title: "Everything Bagels (4)", description: "Four boiled-then-baked bagels with house-made everything seasoning. Chewy, authentic, New York-style.", price: 10.0, quantity: 6, photoUrl: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400", dietaryTags: '["vegan"]', vendorName: "RVA Bread Co", vendorId: 28, categoryIcon: "🥖", categorySlug: "bread-pastries", postType: "baked_today", postedAt: hoursAgo(1.5), pickupWindowStart: pickupToday(7), pickupWindowEnd: pickupToday(13), city: "Richmond", state: "VA" },
  { id: 65, title: "Challah", description: "A beautiful braided challah — rich with eggs, slightly sweet. Perfect for French toast.", price: 11.0, quantity: 4, photoUrl: "https://images.unsplash.com/photo-1549931319-a545799f7b09?w=400", dietaryTags: '["vegetarian"]', vendorName: "RVA Bread Co", vendorId: 28, categoryIcon: "🥖", categorySlug: "bread-pastries", postType: "limited_batch", postedAt: hoursAgo(4), pickupWindowStart: pickupToday(7), pickupWindowEnd: pickupToday(13), city: "Richmond", state: "VA" },
  { id: 66, title: "Pasture-Raised Dozen", description: "A dozen eggs from our pasture-raised flock. The hens roam 5 acres — deep orange yolks, rich flavor.", price: 8.0, quantity: 15, photoUrl: "https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?w=400", dietaryTags: '["vegetarian","gluten-free"]', vendorName: "Virginia Egg Co", vendorId: 29, categoryIcon: "🥚", categorySlug: "eggs-dairy", postType: "available_now", postedAt: minsAgo(10), pickupWindowStart: pickupToday(8), pickupWindowEnd: pickupToday(18), city: "Richmond", state: "VA" },
  { id: 67, title: "Weekend Egg Box", description: "18 eggs + a jar of our house-made hot sauce. Everything for the perfect weekend brunch.", price: 14.0, quantity: 8, photoUrl: "https://images.unsplash.com/photo-1598965675045-8e1e099edc5c?w=400", dietaryTags: '["vegetarian","gluten-free"]', vendorName: "Virginia Egg Co", vendorId: 29, categoryIcon: "🥚", categorySlug: "eggs-dairy", postType: "available_now", postedAt: hoursAgo(3), pickupWindowStart: pickupToday(8), pickupWindowEnd: pickupToday(18), city: "Richmond", state: "VA" },

  // ═══ NORFOLK (IDs 68–71) ═══
  { id: 68, title: "Coastal Salad Box", description: "A box of fresh salad greens, arugula, and edible flowers from our Norfolk greenhouse.", price: 12.0, quantity: 8, photoUrl: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=400", dietaryTags: '["vegan","gluten-free"]', vendorName: "Coastal Produce", vendorId: 30, categoryIcon: "🌽", categorySlug: "produce", postType: "harvested_today", postedAt: minsAgo(35), pickupWindowStart: pickupToday(9), pickupWindowEnd: pickupToday(17), city: "Norfolk", state: "VA" },
  { id: 69, title: "Herb & Pepper Box", description: "Fresh herbs (basil, cilantro, mint) plus bell peppers and jalapeños from our garden.", price: 9.0, quantity: 6, photoUrl: "https://images.unsplash.com/photo-1579113800032-c38bd7635818?w=400", dietaryTags: '["vegan","gluten-free"]', vendorName: "Coastal Produce", vendorId: 30, categoryIcon: "🌽", categorySlug: "produce", postType: "harvested_today", postedAt: hoursAgo(4), pickupWindowStart: pickupToday(9), pickupWindowEnd: pickupToday(17), city: "Norfolk", state: "VA" },
  { id: 70, title: "Mermaid Cupcake Box (6)", description: "Six coastal-inspired cupcakes: key lime, coconut, and sea salt caramel. Ghent's favorite.", price: 20.0, quantity: 5, photoUrl: "https://images.unsplash.com/photo-1558301211-7099e59b9c58?w=400", dietaryTags: '["vegetarian"]', vendorName: "Mermaid Bakery", vendorId: 31, categoryIcon: "🥧", categorySlug: "desserts", postType: "just_made", postedAt: minsAgo(15), pickupWindowStart: pickupToday(11), pickupWindowEnd: pickupToday(17), city: "Norfolk", state: "VA" },
  { id: 71, title: "French Macaron Box (8)", description: "Eight assorted French macarons — pistachio, raspberry, lavender, and vanilla bean.", price: 18.0, quantity: 4, photoUrl: "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400", dietaryTags: '["vegetarian","gluten-free"]', vendorName: "Mermaid Bakery", vendorId: 31, categoryIcon: "🥧", categorySlug: "desserts", postType: "just_made", postedAt: hoursAgo(5), pickupWindowStart: pickupToday(11), pickupWindowEnd: pickupToday(17), city: "Norfolk", state: "VA" },

  // ═══ FAYETTEVILLE (IDs 72–76) ═══
  { id: 72, title: "Ozark Wildflower Honey — 16oz", description: "Pure wildflower honey from the Boston Mountains. Floral, complex, and never heated.", price: 14.0, quantity: 10, photoUrl: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=400", dietaryTags: '["gluten-free"]', vendorName: "Ozark Mountain Honey", vendorId: 32, categoryIcon: "🍯", categorySlug: "honey-preserves", postType: "available_now", postedAt: minsAgo(30), pickupWindowStart: pickupToday(9), pickupWindowEnd: pickupToday(16), city: "Fayetteville", state: "AR" },
  { id: 73, title: "Blackberry Honey — 8oz", description: "Dark, fruity honey from hives placed near wild blackberry patches in the Ozarks.", price: 12.0, quantity: 6, photoUrl: "https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=400", dietaryTags: '["gluten-free"]', vendorName: "Ozark Mountain Honey", vendorId: 32, categoryIcon: "🍯", categorySlug: "honey-preserves", postType: "available_now", postedAt: hoursAgo(6), pickupWindowStart: pickupToday(9), pickupWindowEnd: pickupToday(16), city: "Fayetteville", state: "AR" },
  { id: 74, title: "Honeycomb Square — 6oz", description: "A block of raw honeycomb from our Ozark hives. Perfect for cheese boards.", price: 9.0, quantity: 4, photoUrl: "https://images.unsplash.com/photo-1471943311424-646960669fbc?w=400", dietaryTags: '["gluten-free"]', vendorName: "Ozark Mountain Honey", vendorId: 32, categoryIcon: "🍯", categorySlug: "honey-preserves", postType: "limited_batch", postedAt: daysAgo(1), pickupWindowStart: pickupToday(9), pickupWindowEnd: pickupToday(16), city: "Fayetteville", state: "AR" },
  { id: 75, title: "NWA Veggie Box", description: "A box of fresh Northwest Arkansas produce — tomatoes, peppers, squash, and melons from our family farm.", price: 20.0, quantity: 6, photoUrl: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=400", dietaryTags: '["vegan","gluten-free"]', vendorName: "Razorback Produce", vendorId: 33, categoryIcon: "🌽", categorySlug: "produce", postType: "harvested_today", postedAt: minsAgo(18), pickupWindowStart: pickupToday(9), pickupWindowEnd: pickupToday(17), city: "Fayetteville", state: "AR" },
  { id: 76, title: "Ozark Melon Basket", description: "2-3 ripe melons (cantaloupe, watermelon, or honeydew) from our sun-soaked patch.", price: 10.0, quantity: 6, photoUrl: "https://images.unsplash.com/photo-1579113800032-c38bd7635818?w=400", dietaryTags: '["vegan","gluten-free"]', vendorName: "Razorback Produce", vendorId: 33, categoryIcon: "🌽", categorySlug: "produce", postType: "harvested_today", postedAt: hoursAgo(5), pickupWindowStart: pickupToday(9), pickupWindowEnd: pickupToday(17), city: "Fayetteville", state: "AR" },

  // ═══ WICHITA (IDs 77–80) ═══
  { id: 77, title: "Sunflower Seed Cookies (6)", description: "Buttery shortbread cookies studded with Kansas sunflower seeds. Our signature treat.", price: 12.0, quantity: 8, photoUrl: "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=400", dietaryTags: '["vegetarian"]', vendorName: "Prairie Flower Bakery", vendorId: 34, categoryIcon: "🥧", categorySlug: "desserts", postType: "baked_today", postedAt: minsAgo(25), pickupWindowStart: pickupToday(10), pickupWindowEnd: pickupToday(16), city: "Wichita", state: "KS" },
  { id: 78, title: "Flint Hills Honey Cake", description: "A moist, spiced honey cake made with Kansas wildflower honey. The taste of the prairie.", price: 18.0, quantity: 4, photoUrl: "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400", dietaryTags: '["vegetarian"]', vendorName: "Prairie Flower Bakery", vendorId: 34, categoryIcon: "🥧", categorySlug: "desserts", postType: "limited_batch", postedAt: hoursAgo(3), pickupWindowStart: pickupToday(10), pickupWindowEnd: pickupToday(16), city: "Wichita", state: "KS" },
  { id: 79, title: "Prairie Fresh Dozen", description: "One dozen farm-fresh eggs from our Wichita homestead. Deep golden yolks from happy, free-range hens.", price: 7.0, quantity: 15, photoUrl: "https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?w=400", dietaryTags: '["vegetarian","gluten-free"]', vendorName: "Sunflower State Eggs", vendorId: 35, categoryIcon: "🥚", categorySlug: "eggs-dairy", postType: "available_now", postedAt: minsAgo(12), pickupWindowStart: pickupToday(8), pickupWindowEnd: pickupToday(18), city: "Wichita", state: "KS" },
  { id: 80, title: "Egg Lover's Half Flat", description: "30 eggs — two and a half dozen from our best layers. Stock up for the week.", price: 15.0, quantity: 6, photoUrl: "https://images.unsplash.com/photo-1598965675045-8e1e099edc5c?w=400", dietaryTags: '["vegetarian","gluten-free"]', vendorName: "Sunflower State Eggs", vendorId: 35, categoryIcon: "🥚", categorySlug: "eggs-dairy", postType: "available_now", postedAt: hoursAgo(4), pickupWindowStart: pickupToday(8), pickupWindowEnd: pickupToday(18), city: "Wichita", state: "KS" },
];

// Attach expiresAt to all mock listings
export const MOCK_LISTINGS_WITH_EXPIRY = MOCK_LISTINGS.map((l) => ({
  ...l,
  expiresAt: expireAfter(l.postedAt),
}));

// ── Reviews ──────────────────────────────────────────────────────────
export const MOCK_REVIEWS: Record<string, any[]> = {
  "1": [
    { id: 1, userId: "user_1", userName: "Sam T.", rating: 5, comment: "Best sourdough in Austin! The crust is perfectly crackly and the crumb is so open and chewy.", createdAt: daysAgo(7) },
    { id: 2, userId: "user_2", userName: "Dana K.", rating: 4, comment: "Love the country loaf. Wish they had more availability on weekends!", createdAt: daysAgo(14) },
    { id: 3, userId: "user_5", userName: "Mike R.", rating: 5, comment: "The Everything Bagel sourdough is incredible. Toasted with cream cheese... chef's kiss!", createdAt: daysAgo(3) },
  ],
  "2": [
    { id: 4, userId: "user_1", userName: "Sam T.", rating: 5, comment: "These eggs are incredible — the yolks are so orange! You can taste the difference.", createdAt: daysAgo(5) },
    { id: 5, userId: "user_3", userName: "Lila M.", rating: 5, comment: "I pick up a dozen every Saturday. These are the best eggs I've ever had.", createdAt: daysAgo(10) },
  ],
  "4": [
    { id: 7, userId: "user_3", userName: "Lila M.", rating: 5, comment: "The pecan pie is absolutely divine. Worth every penny.", createdAt: daysAgo(30) },
    { id: 8, userId: "user_6", userName: "Jordan P.", rating: 5, comment: "Best pie I've had in Texas. Patricia is a true artisan.", createdAt: daysAgo(2) },
  ],
  "5": [
    { id: 10, userId: "user_2", userName: "Dana K.", rating: 5, comment: "Amazing veggie box. Everything was super fresh. The heirloom tomatoes were the highlight!", createdAt: daysAgo(4) },
  ],
  "11": [
    { id: 11, userId: "user_10", userName: "Nashville Nate", rating: 5, comment: "Dolly's Country Loaf is the real deal. Best bread I've had in Tennessee!", createdAt: daysAgo(6) },
  ],
  "13": [
    { id: 12, userId: "user_11", userName: "Eastside Ellie", rating: 5, comment: "These eggs are gorgeous. You can tell the hens are well cared for.", createdAt: daysAgo(3) },
  ],
  "14": [
    { id: 13, userId: "user_12", userName: "VolFan99", rating: 5, comment: "The Tennessee Whiskey Cake is insanely good. Brought it to a tailgate and it disappeared in minutes!", createdAt: daysAgo(8) },
  ],
  "16": [
    { id: 14, userId: "user_13", userName: "ChattaFoodie", rating: 5, comment: "The Caramel Crunch cookies are dangerously good. Ordering again tomorrow!", createdAt: daysAgo(2) },
  ],
  "21": [
    { id: 15, userId: "user_14", userName: "AVL Bread Fan", rating: 5, comment: "Blue Ridge Bakers makes the most incredible wood-fired sourdough. Worth the drive from anywhere in Asheville.", createdAt: daysAgo(5) },
  ],
  "35": [
    { id: 16, userId: "user_15", userName: "ICT Local", rating: 5, comment: "Best eggs in Kansas. The yolks are so orange and rich. Never going back to supermarket eggs.", createdAt: daysAgo(7) },
  ],
};
